before:
  hooks:
    - go mod download
builds:
  - main: ./cmd/protoc-gen-gapi-lint/main.go
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - arm
      - arm64
      - amd64
changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
